version: '3'
services: 
  boom-sports:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 127.0.0.1:80:3000
      - 127.0.0.1:9229:9229
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
      - ./templates:/usr/src/app/templates